name: Build and Push Docker Image

on:
  workflow_dispatch:

env:
  ECR_URI: 497863501987.dkr.ecr.ap-south-1.amazonaws.com/dev/face-matrix/api
  IMAGE_TAG: latest
  AWS_REGION: ap-south-1

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build --no-cache -t $ECR_URI:$IMAGE_TAG .

  push:
    name: Push to ECR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image..."
          docker push $ECR_URI:$IMAGE_TAG

  cleanup:
    name: Cleanup Docker Resources
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Cleanup Docker
        run: |
          echo "Cleaning up Docker resources..."
          docker rmi $ECR_URI:$IMAGE_TAG || true
          docker system prune -f || true